import 'package:flutter/material.dart';

import '../services/translations.dart';
import '../theme/app_colors.dart';
import '../widgets/common.dart';

/// Privacy Policy screen.
class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final s = S.of(context);
    final isFr = s.language == 'LANGUE';
    return GradientScaffold(
      appBar: AppBar(
        title: Text(s.privacyPolicy),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(18, 18, 18, 28),
        children: [
          Text(
            isFr ? 'ScoutAI — Politique de confidentialité' : 'ScoutAI — Privacy Policy',
            style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 24),
          ),
          const SizedBox(height: 8),
          Text(
            isFr ? 'Dernière mise à jour : février 2026' : 'Last updated: February 2026',
            style: TextStyle(color: AppColors.txMuted(context), fontSize: 13),
          ),
          const SizedBox(height: 20),
          _section(
            isFr ? '1. Données collectées' : '1. Data We Collect',
            isFr
                ? 'Nous collectons votre adresse email, nom, position, nationalité et les vidéos que vous envoyez. Les analyses sont générées par notre moteur IA à partir de vos vidéos.'
                : 'We collect your email address, name, position, nationality, and videos you upload. Analyses are generated by our AI engine from your videos.',
          ),
          _section(
            isFr ? '2. Utilisation des données' : '2. How We Use Your Data',
            isFr
                ? 'Vos données sont utilisées pour fournir le service ScoutAI : analyse vidéo, statistiques de performance, et fonctionnalités de marketplace pour les recruteurs.'
                : 'Your data is used to provide the ScoutAI service: video analysis, performance statistics, and marketplace features for scouters.',
          ),
          _section(
            isFr ? '3. Stockage et sécurité' : '3. Storage & Security',
            isFr
                ? 'Les données sont stockées de manière sécurisée. Les mots de passe sont hashés. Les vidéos sont transmises via des connexions chiffrées.'
                : 'Data is stored securely. Passwords are hashed. Videos are transmitted over encrypted connections.',
          ),
          _section(
            isFr ? '4. Partage de données' : '4. Data Sharing',
            isFr
                ? 'Nous ne vendons pas vos données. Les profils des joueurs sont visibles par les recruteurs sur la marketplace. Vous pouvez contrôler la visibilité de votre profil.'
                : 'We do not sell your data. Player profiles are visible to scouters on the marketplace. You can control your profile visibility.',
          ),
          _section(
            isFr ? '5. Vos droits' : '5. Your Rights',
            isFr
                ? 'Vous pouvez modifier ou supprimer votre compte à tout moment depuis les paramètres du profil. Toutes les données associées seront supprimées.'
                : 'You can edit or delete your account at any time from the profile settings. All associated data will be removed.',
          ),
          _section(
            isFr ? '6. Contact' : '6. Contact',
            isFr
                ? 'Pour toute question, contactez-nous à support@scoutai.app'
                : 'For questions, contact us at support@scoutai.app',
          ),
        ],
      ),
    );
  }

  Widget _section(String title, String body) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 18),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 16)),
          const SizedBox(height: 6),
          Text(body, style: const TextStyle(fontSize: 14, height: 1.5)),
        ],
      ),
    );
  }
}
